### ISSUE TITLE
when I npm start the console just show + 158 hidden modules...?

### ISSUE THREAD

**Issue by masonlin** [jarsbe/flux-starter-kit#2]
Version: webpack 1.12.2
Time: 1903ms
                   Asset    Size  Chunks             Chunk Names
./dist/scripts/bundle.js  612 kB       0  [emitted]  main
    + 158 hidden modules
_

what step do I less to do?

Thank you.

**Comment by jackcallister** [comment]
So now that the JavaScript is bundled a server should be serving the application. Visit [http://localhost:8000](http://localhost:8000) - does that solve your problem?

**Comment by masonlin** [comment]
Thank you very much, I have solved this problem.

**Comment by jackcallister** [comment]
Wonderful :)

**Comment by dBolnick** [comment]
Hey, I have the same issue. I have visited http://localhost:8000 and I am not receiving anything. thanks
